server {
 listen 80;
 root /usr/share/nginx/html;
 client_max_body_size 5m;
 location /api/ {
  proxy_pass http://notes:8080;
  proxy_http_version 1.1;
  proxy_set_header Host $http_host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_buffering off;
  proxy_read_timeout 65s;
 }
 location / { try_files $uri $uri/ =404; }
 location = /service-worker.js { add_header Cache-Control "no-cache"; }
 location /_app/immutable/ { add_header Cache-Control "public, max-age=31536000, immutable"; }
}
